
name: Daily News Digest

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install openai mailerlite
      - name: Run main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAILERLITE_API_KEY: ${{ secrets.MAILERLITE_API_KEY }}
          MAILERLITE_GROUP_ID: ${{ secrets.MAILERLITE_GROUP_ID }}
        run: python main.py
